#!/usr/bin/env python3
"""Generate packaging copies from the canonical Unleak skill and rule files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CANONICAL_SKILL = ROOT / "skills" / "unleak" / "SKILL.md"
CANONICAL_RULE = ROOT / "rules" / "unleak-activate.md"

VERSION = "0.1.0"
WEDGE = (
    "Privacy-preserving local analysis for coding agents: compute on raw data "
    "locally, release only validated derived artifacts to the model."
)
TARGET_USERS = (
    "Teams using coding agents on sensitive local CSV, SQLite, and project data."
)

GENERATED_FILES = {
    ROOT / "SKILL.md": "root_skill",
    ROOT / ".claude-plugin" / "SKILL.md": "claude_skill",
    ROOT / ".claude-plugin" / "rules" / "unleak-activate.md": "claude_rule",
    ROOT / ".claude-plugin" / "manifest.json": "claude_manifest",
    ROOT / "plugins" / "unleak" / "SKILL.md": "codex_skill",
    ROOT / "plugins" / "unleak" / "rules" / "unleak-activate.md": "codex_rule",
    ROOT / "plugins" / "unleak" / ".codex-plugin" / "plugin.json": "codex_plugin",
    ROOT / "gemini-extension.json": "gemini_manifest",
}


def parse_frontmatter(markdown: str) -> dict[str, str]:
    if not markdown.startswith("---\n"):
        raise ValueError("canonical skill is missing YAML frontmatter")
    _, frontmatter, _ = markdown.split("---\n", 2)
    result: dict[str, str] = {}
    for line in frontmatter.strip().splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = value.strip()
    return result


def generated_skill_copy(canonical_skill: str, destination: Path) -> str:
    return (
        f"<!-- Generated by scripts/sync_packaging.py from "
        f"{CANONICAL_SKILL.relative_to(ROOT)} for {destination.relative_to(ROOT)}. -->\n"
        f"{canonical_skill}"
    )


def generated_rule_copy(canonical_rule: str, destination: Path) -> str:
    return (
        f"<!-- Generated by scripts/sync_packaging.py from "
        f"{CANONICAL_RULE.relative_to(ROOT)} for {destination.relative_to(ROOT)}. -->\n"
        f"{canonical_rule}"
    )


def dump_json(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def build_outputs() -> dict[Path, str]:
    canonical_skill = CANONICAL_SKILL.read_text()
    canonical_rule = CANONICAL_RULE.read_text()
    metadata = parse_frontmatter(canonical_skill)

    base = {
        "name": metadata.get("name", "unleak"),
        "version": VERSION,
        "description": metadata.get("description", ""),
        "product_wedge": WEDGE,
        "target_users": TARGET_USERS,
        "primary_targets": ["codex", "claude"],
        "secondary_targets": ["gemini"],
        "rules": ["rules/unleak-activate.md"],
    }

    return {
        ROOT / "SKILL.md": canonical_skill,
        ROOT / ".claude-plugin" / "SKILL.md": generated_skill_copy(
            canonical_skill, ROOT / ".claude-plugin" / "SKILL.md"
        ),
        ROOT / ".claude-plugin" / "rules" / "unleak-activate.md": generated_rule_copy(
            canonical_rule, ROOT / ".claude-plugin" / "rules" / "unleak-activate.md"
        ),
        ROOT / ".claude-plugin" / "manifest.json": dump_json(
            {
                **base,
                "entrypoint": "SKILL.md",
                "schema_version": 1,
                "kind": "claude-skill-package",
            }
        ),
        ROOT / "plugins" / "unleak" / "SKILL.md": generated_skill_copy(
            canonical_skill, ROOT / "plugins" / "unleak" / "SKILL.md"
        ),
        ROOT / "plugins" / "unleak" / "rules" / "unleak-activate.md": generated_rule_copy(
            canonical_rule, ROOT / "plugins" / "unleak" / "rules" / "unleak-activate.md"
        ),
        ROOT / "plugins" / "unleak" / ".codex-plugin" / "plugin.json": dump_json(
            {
                **base,
                "entrypoint": "SKILL.md",
                "schema_version": 1,
                "kind": "codex-plugin",
                "id": "unleak",
            }
        ),
        ROOT / "gemini-extension.json": dump_json(
            {
                **base,
                "entrypoint": "skills/unleak/SKILL.md",
                "schema_version": 1,
                "kind": "gemini-extension",
                "tier": "secondary",
            }
        ),
    }


def write_outputs(outputs: dict[Path, str]) -> list[Path]:
    written: list[Path] = []
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(path)
    return written


def check_outputs(outputs: dict[Path, str]) -> list[Path]:
    mismatches: list[Path] = []
    for path, expected in outputs.items():
        if not path.exists() or path.read_text() != expected:
            mismatches.append(path)
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated files are current")
    args = parser.parse_args()

    outputs = build_outputs()

    if args.check:
        mismatches = check_outputs(outputs)
        if mismatches:
            for path in mismatches:
                print(path.relative_to(ROOT))
            return 1
        return 0

    for path in write_outputs(outputs):
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
