#!/usr/bin/env python3
"""Generate mirrored install-surface copies from canonical Unleak files."""

from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CANONICAL_SKILL = ROOT / "skills" / "unleak" / "SKILL.md"
CANONICAL_RULE = ROOT / "rules" / "unleak-activate.md"

VERSION = "0.1.0"
WEDGE = (
    "Privacy-preserving local analysis for coding agents: compute on raw data "
    "locally, release only validated derived artifacts to the model."
)
TARGET_USERS = (
    "Teams using coding agents on sensitive local CSV, SQLite, and project data."
)

GENERATED_FILES = {
    ROOT / ".agents" / "plugins" / "marketplace.json": "repo_marketplace",
    ROOT / ".clinerules" / "unleak.md": "cline_rule",
    ROOT / ".cursor" / "rules" / "unleak.mdc": "cursor_rule",
    ROOT / ".cursor" / "skills" / "unleak" / "SKILL.md": "cursor_skill",
    ROOT / ".claude-plugin" / "rules" / "unleak-activate.md": "claude_rule",
    ROOT / ".claude-plugin" / "plugin.json": "claude_plugin",
    ROOT / ".claude-plugin" / "marketplace.json": "claude_marketplace",
    ROOT / ".claude-plugin" / "manifest.json": "claude_manifest",
    ROOT / ".codex" / "hooks.json": "codex_hooks",
    ROOT / ".github" / "copilot-instructions.md": "copilot_rule",
    ROOT / ".windsurf" / "rules" / "unleak.md": "windsurf_rule",
    ROOT / ".windsurf" / "skills" / "unleak" / "SKILL.md": "windsurf_skill",
    ROOT / "unleak" / "SKILL.md": "repo_skill",
    ROOT / "unleak.skill": "skill_zip",
    ROOT / "plugins" / "unleak" / "rules" / "unleak-activate.md": "codex_rule",
    ROOT / "plugins" / "unleak" / ".codex-plugin" / "plugin.json": "codex_plugin",
    ROOT / "plugins" / "unleak" / "skills" / "unleak" / "SKILL.md": "plugin_skill",
    ROOT / "gemini-extension.json": "gemini_manifest",
}


def parse_frontmatter(markdown: str) -> dict[str, str]:
    if not markdown.startswith("---\n"):
        raise ValueError("canonical skill is missing YAML frontmatter")
    _, frontmatter, _ = markdown.split("---\n", 2)
    result: dict[str, str] = {}
    for line in frontmatter.strip().splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = value.strip()
    return result


def generated_rule_copy(canonical_rule: str, destination: Path) -> str:
    return (
        f"<!-- Generated by scripts/sync_packaging.py from "
        f"{CANONICAL_RULE.relative_to(ROOT)} for {destination.relative_to(ROOT)}. -->\n"
        f"{canonical_rule}"
    )


def dump_json(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def cursor_rule(canonical_rule: str) -> str:
    return (
        "---\n"
        'description: "Unleak auto-activation for sensitive local analysis"\n'
        "alwaysApply: true\n"
        "---\n\n"
        f"{canonical_rule}"
    )


def windsurf_rule(canonical_rule: str) -> str:
    return "---\ntrigger: always_on\n---\n\n" + canonical_rule


def codex_hook_text() -> str:
    prompt = (
        "UNLEAK ACTIVE. Use it when asked to analyze sensitive local CSV, SQLite, or project "
        "data. Keep raw rows local. Discover metadata first. Confirm risk classes when needed. "
        "Create deterministic local scripts for safe aggregates, aliases, indexes, buckets, or "
        "percentiles. Validate artifact plus lineage before model use. Never export raw rows, "
        "free text, direct identifiers, secrets, or exact protected business metrics when policy "
        "only allows coarser releases."
    )
    return dump_json(
        {
            "hooks": {
                "SessionStart": [
                    {
                        "type": "command",
                        "command": f"echo '{prompt}'",
                    }
                ]
            }
        }
    )


def build_skill_zip_bytes() -> bytes:
    skill_text = CANONICAL_SKILL.read_text(encoding="utf-8")
    from io import BytesIO

    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("unleak/SKILL.md", skill_text)
    return buffer.getvalue()


def build_outputs() -> dict[Path, str]:
    canonical_skill = CANONICAL_SKILL.read_text(encoding="utf-8")
    canonical_rule = CANONICAL_RULE.read_text(encoding="utf-8")
    metadata = parse_frontmatter(canonical_skill)

    base = {
        "name": metadata.get("name", "unleak"),
        "version": VERSION,
        "description": metadata.get("description", ""),
        "product_wedge": WEDGE,
        "target_users": TARGET_USERS,
        "primary_targets": ["codex", "claude"],
        "secondary_targets": ["gemini"],
        "rules": ["rules/unleak-activate.md"],
    }

    return {
        ROOT / ".agents" / "plugins" / "marketplace.json": dump_json(
            {
                "name": "unleak-repo",
                "interface": {"displayName": "Unleak Repo"},
                "plugins": [
                    {
                        "name": "unleak",
                        "source": {"source": "local", "path": "./plugins/unleak"},
                        "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
                        "category": "Security",
                    }
                ],
            }
        ),
        ROOT / ".clinerules" / "unleak.md": canonical_rule,
        ROOT / ".cursor" / "rules" / "unleak.mdc": cursor_rule(canonical_rule),
        ROOT / ".cursor" / "skills" / "unleak" / "SKILL.md": canonical_skill,
        ROOT / ".claude-plugin" / "rules" / "unleak-activate.md": generated_rule_copy(
            canonical_rule, ROOT / ".claude-plugin" / "rules" / "unleak-activate.md"
        ),
        ROOT / ".claude-plugin" / "plugin.json": dump_json(
            {
                "name": "unleak",
                "description": metadata.get("description", ""),
                "author": {
                    "name": "Sainy",
                    "url": "https://github.com/sainy",
                },
                "hooks": {
                    "UserPromptSubmit": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": 'python3 "$CLAUDE_PROJECT_DIR/scripts/unleak_hook.py" user-prompt',
                                    "timeout": 5,
                                    "statusMessage": "Checking unleak policy...",
                                }
                            ]
                        }
                    ],
                    "PreToolUse": [
                        {
                            "matcher": "Bash|Read",
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": 'python3 "$CLAUDE_PROJECT_DIR/scripts/unleak_hook.py" pre-tool',
                                    "timeout": 5,
                                    "statusMessage": "Blocking unsafe raw-data access...",
                                }
                            ],
                        }
                    ],
                    "PostToolUse": [
                        {
                            "matcher": "Bash",
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": 'python3 "$CLAUDE_PROJECT_DIR/scripts/unleak_hook.py" post-tool',
                                    "timeout": 5,
                                    "statusMessage": "Validating derived release artifacts...",
                                }
                            ],
                        }
                    ],
                },
            }
        ),
        ROOT / ".claude-plugin" / "marketplace.json": dump_json(
            {
                "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
                "name": "unleak",
                "description": "Privacy-preserving local analysis for Claude Code.",
                "owner": {
                    "name": "Sainy",
                    "url": "https://github.com/sainy",
                },
                "plugins": [
                    {
                        "name": "unleak",
                        "description": "Keep raw data local. Release only validated derived artifacts.",
                        "source": "./",
                        "category": "security",
                    }
                ],
            }
        ),
        ROOT / ".claude-plugin" / "manifest.json": dump_json(
            {
                **base,
                "entrypoint": "skills/unleak/SKILL.md",
                "schema_version": 1,
                "kind": "claude-skill-package",
            }
        ),
        ROOT / ".codex" / "hooks.json": codex_hook_text(),
        ROOT / ".github" / "copilot-instructions.md": canonical_rule,
        ROOT / ".windsurf" / "rules" / "unleak.md": windsurf_rule(canonical_rule),
        ROOT / ".windsurf" / "skills" / "unleak" / "SKILL.md": canonical_skill,
        ROOT / "unleak" / "SKILL.md": canonical_skill,
        ROOT / "plugins" / "unleak" / "rules" / "unleak-activate.md": generated_rule_copy(
            canonical_rule, ROOT / "plugins" / "unleak" / "rules" / "unleak-activate.md"
        ),
        ROOT / "plugins" / "unleak" / ".codex-plugin" / "plugin.json": dump_json(
            {
                "name": "unleak",
                "version": VERSION,
                "description": "Keep raw data local. Validate derived artifacts before model use.",
                "author": {
                    "name": "Sainy",
                    "url": "https://github.com/sainy",
                },
                "license": "MIT",
                "keywords": ["privacy", "security", "analysis", "data", "agents"],
                "skills": "./skills/",
                "interface": {
                    "displayName": "Unleak",
                    "shortDescription": "Analyze sensitive data with minimal leakage.",
                    "longDescription": (
                        "Local-first analysis for coding agents. Discover sources, classify risk, "
                        "compute deterministic safe artifacts locally, and validate release before "
                        "the model sees anything."
                    ),
                    "developerName": "Sainy",
                    "category": "Security",
                    "capabilities": ["Read", "Write"],
                    "privacyPolicyURL": "https://github.com/sainy/unleak/blob/main/docs/threat-model.md",
                    "termsOfServiceURL": "https://github.com/sainy/unleak/blob/main/LICENSE",
                    "defaultPrompt": [
                        "Use $unleak when analyzing sensitive local CSV, SQLite, or project data."
                    ],
                    "composerIcon": "./assets/unleak-small.svg",
                    "logo": "./assets/unleak.svg",
                    "screenshots": [],
                    "brandColor": "#0F766E",
                },
            }
        ),
        ROOT / "plugins" / "unleak" / "skills" / "unleak" / "SKILL.md": canonical_skill,
        ROOT / "gemini-extension.json": dump_json(
            {
                **base,
                "entrypoint": "skills/unleak/SKILL.md",
                "schema_version": 1,
                "kind": "gemini-extension",
                "tier": "secondary",
            }
        ),
    }


def write_outputs(outputs: dict[Path, str]) -> list[Path]:
    written: list[Path] = []
    for path, content in outputs.items():
        if path.name == "unleak.skill":
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    zip_path = ROOT / "unleak.skill"
    zip_path.write_bytes(build_skill_zip_bytes())
    written.append(zip_path)
    return written


def check_outputs(outputs: dict[Path, str]) -> list[Path]:
    mismatches: list[Path] = []
    for path, expected in outputs.items():
        if path.name == "unleak.skill":
            if not path.exists() or path.read_bytes() != build_skill_zip_bytes():
                mismatches.append(path)
            continue
        if not path.exists() or path.read_text() != expected:
            mismatches.append(path)
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated files are current")
    args = parser.parse_args()

    outputs = build_outputs()

    if args.check:
        mismatches = check_outputs(outputs)
        if mismatches:
            for path in mismatches:
                print(path.relative_to(ROOT))
            return 1
        return 0

    for path in write_outputs(outputs):
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
